%global commit0 4936a7da7a233e22cc71f2d11583f55640b7c8ed
%global shortcommit0 %(c=%{commit0}; echo ${c:0:7})

%define _package_name Netdot-Client-REST

Name:           perl-Netdot-Client-REST
Version:        1.03.1
Release:        1%{?dist}
Summary:        RESTful API for Netdot
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            https://github.com/ksyz/Netdot-Client-REST/
Source0:        https://github.com/ksyz/%{_package_name}/archive/%{commit0}.tar.gz#/%{name}-%{shortcommit0}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(LWP)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(XML::Simple)
Requires:       perl(Data::Dumper)
Requires:       perl(LWP)
Requires:       perl(XML::Simple)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Netdot::Client::REST can be used in Perl scripts that need access to the
Netdot application database. Communication occurs over HTTP/HTTPS, thus
avoiding the need to open SQL access on the machine running Netdot.

%prep
%autosetup -n %{_package_name}-%{commit0}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf %{buildroot}

./Build install destdir=%{buildroot} create_packlist=0
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

install -m 755 -d %{buildroot}/%{_bindir}/
install -m 755 ndview %{buildroot}/%{_bindir}/
install -m 755 nd_zone_import %{buildroot}/%{_bindir}/

%check
./Build test

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%doc META.json
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_bindir}/*

%changelog
* Thu Aug  9 2016 Michal Ingeli <mi@v3.sk> 1.03.1-1
- Migrated to other upstream
- Added utility script from new fork

* Fri Nov 13 2015 Michal Ingeli <mi@v3.sk> 1.03-1
- Specfile autogenerated by cpanspec 1.78.
